### ISSUE TITLE
Do not create a new Interface instance when updating

### ISSUE THREAD

**Issue by ajoaoff** [kytos-ng/of_core#3]
Original issue opened by @ajoaoff at https://github.com/kytos/of_core/issues/35.

When an event of `port_change` is received, do not create a new instance of `Interface` if one already exists, but update it.

**Comment by viniarck** [comment]
I'll go ahead and close this issue. 

As of now, we've been updating interfaces when handling port description or port status `OFPPR_ADD`:

https://github.com/kytos-ng/of_core/blob/master/v0x04/utils.py#L110

https://github.com/kytos-ng/of_core/blob/master/main.py#L591
